# @Time: 2023年06月19日 11:57
# @Author: orcakill
# @File: enum.py
# @Description: 常量


class Onmyoji:
    awaken_ZB = r"探索\觉醒\准备"
    awaken_CZ = r"探索\觉醒\出战"
    awaken_JC = r"探索\觉醒\加成"
    awaken_JCG = r"探索\觉醒\加成关"
    awaken_JCK = r"探索\觉醒\加成开"
    awaken_XZSS = r"探索\觉醒\协战式神"
    awaken_C = r"探索\觉醒\层字"
    awaken_ZDSL = r"探索\觉醒\战斗胜利"
    awaken_ZDSB = r"探索\觉醒\战斗失败"
    awaken_ZCTZ = r"探索\觉醒\再次挑战"
    awaken_TZ = r"探索\觉醒\挑战"
    awaken_HBD = r"探索\觉醒\换白蛋"
    awaken_DJDB = r"探索\觉醒\点击地板"
    awaken_BD = r"探索\觉醒\白蛋"
    awaken_JXJC = r"探索\觉醒\觉醒加成"
    awaken_JXBT = r"探索\觉醒\觉醒图标"
    awaken_JSZR = r"探索\觉醒\解锁阵容"
    awaken_TCTZ = r"探索\觉醒\退出挑战"
    awaken_SDZR = r"探索\觉醒\锁定阵容"
    awaken_DW1 = r"探索\觉醒\队伍1"
    awaken_YS = r"探索\觉醒\预设"
    awaken_SC = r"探索\觉醒\十层"
    awaken_QL_F = r"探索\觉醒\麒麟图标\风麒麟"
    awaken_QL_H = r"探索\觉醒\麒麟图标\火麒麟"
    awaken_QL_S = r"探索\觉醒\麒麟图标\水麒麟"
    awaken_QL_L = r"探索\觉醒\麒麟图标\雷麒麟"

    border_GRJJ = r"探索\结界突破\个人结界"
    border_GRJJWSB = r"探索\结界突破\个人结界无失败"
    border_GTRQ = r"探索\结界突破\呱太入侵"
    border_JG = r"探索\结界突破\进攻"
    border_JJSY = r"探索\结界突破\结界首页"
    border_JJTPTB = r"探索\结界突破\结界突破图标"
    border_JJTZJWP = r"探索\结界突破\结界挑战劵误判"
    border_JSTXDH = r"探索\结界突破\角色头像大号"
    border_JSTXXH = r"探索\结界突破\角色头像小号"
    border_SDZR = r"探索\结界突破\锁定阵容"
    border_SX = r"探索\结界突破\刷新"
    border_SXQD = r"探索\结界突破\刷新确定"
    border_WJJTZJ = r"探索\结界突破\无结界挑战劵"
    border_XH = r"探索\结界突破\消耗"
    border_YSJTP = r"探索\结界突破\右上角突破"
    border_YSJTPDB = r"探索\结界突破\右上角突破底部"
    border_ZB = r"探索\结界突破\准备"
    border_ZBBZ = r"探索\结界突破\战败标志"
    border_TCTZ = r"探索\结界突破\退出挑战"
    border_ZCTZ = r"探索\结界突破\再次挑战"
    border_ZDSB = r"探索\结界突破\战斗失败"
    border_ZDSL = r"探索\结界突破\战斗胜利"

    comm_FH_LSYXBSXYH = r"通用\返回\蓝色圆形白色小于号"
    comm_FH_SYHDBSCH = r"通用\返回\首页红底白色叉号"
    comm_FH_XSFYHSCH = r"通用\返回\悬赏封印红色叉号"
    comm_FH_YSJZDHBSCH = r"通用\返回\右上角棕底红白色叉号"
    comm_FH_ZSJHKHSXYH = r"通用\返回\左上角黄框黄色小于号"
    comm_FH_ZSJZKDZSHXJT = r"通用\返回\左上角棕框淡棕色回型箭头"

    home_DBCD = r"首页\底部菜单"
    home_DBCDDK = r"首页\底部菜单打开"
    home_QX = r"首页\取消"
    home_TS = r"首页\探索"
    home_XZ = r"首页\下载"

    home_reward_GYXZR = r"首页\奖励\勾玉小纸人"
    home_reward_QBLQ = r"首页\奖励\全部领取"
    home_reward_TLXZR = r"首页\奖励\体力小纸人"
    home_reward_YHJXJCXZR = r"首页\奖励\御魂觉醒加成小纸人"
    home_reward_MRYQ = r"首页\奖励\每日一签"
    home_reward_QDXZR = r"首页\奖励\签到小纸人"
    home_reward_HDJL = r"首页\奖励\获得奖励"
    home_reward_YX = r"首页\奖励\邮箱"
    home_reward_QD = r"首页\奖励\确定"
    home_reward_TCTZ = r"首页\奖励\退出挑战"
    home_DZ = r"首页\町中"

    store_SDTB = r"商店\商店图标"
    store_LBW = r"商店\礼包屋"
    store_MRLQ = r"商店\每日领取"
    store_HDJL = r"商店\获得奖励"

    login_CY = r"登录\常用"
    login_DLAN = r"登录\登录按钮"
    login_FWQ = r"登录\服务器"
    login_KSYX = r"登录\开始游戏"
    login_QHFWQ = r"登录\切换服务器"
    login_QHZH = r"登录\切换账号"
    login_SLTS = r"登录\适龄提示"
    login_TYCS = r"登录\特邀测试"
    login_WYYX = r"登录\网易游戏"
    login_XSJ = r"登录\小三角"
    login_YHZX = r"登录\用户中心"
    login_ZXJS = r"登录\注销角色"

    soul_BQ_GBJC = r"探索\御魂\八岐大蛇\关闭加成"
    soul_BQ_ZB = r"探索\御魂\八岐大蛇\准备"
    soul_BQ_JC = r"探索\御魂\八岐大蛇\加成"
    soul_BQ_JCG = r"探索\御魂\八岐大蛇\加成关"
    soul_BQ_JCK = r"探索\御魂\八岐大蛇\加成开"
    soul_BQ_XZSS = r"探索\御魂\八岐大蛇\协战式神"
    soul_BQ_FXBZ = r"探索\御魂\八岐大蛇\发现宝藏"
    soul_BQ_WS = r"探索\御魂\八岐大蛇\喂食"
    soul_BQ_WSXSJ = r"探索\御魂\八岐大蛇\喂食小三角"
    soul_BQ_CW = r"探索\御魂\八岐大蛇\宠物"
    soul_BQ_CWJL = r"探索\御魂\八岐大蛇\宠物奖励"
    soul_BQ_CZ = r"探索\御魂\八岐大蛇\层字"
    soul_BQ_KQJC = r"探索\御魂\八岐大蛇\开启加成"
    soul_BQ_YHJC = r"探索\御魂\八岐大蛇\御魂加成"
    soul_BQ_ZDSB = r"探索\御魂\八岐大蛇\战斗失败"
    soul_BQ_TZ = r"探索\御魂\八岐大蛇\挑战"
    soul_BQ_DJDB = r"探索\御魂\八岐大蛇\点击地板"
    soul_BQ_BD = r"探索\御魂\八岐大蛇\白蛋"
    soul_BQ_ZD = r"探索\御魂\八岐大蛇\自动"
    soul_BQ_HDJL = r"探索\御魂\八岐大蛇\获得奖励"
    soul_BQ_JSTXDH = r"探索\御魂\八岐大蛇\角色头像大号"
    soul_BQ_JSTXDS = r"探索\御魂\八岐大蛇\角色头像打手"
    souL_BQ_JSTXXH = r"探索\御魂\八岐大蛇\角色头像小号"
    soul_BQ_JSZR = r"探索\御魂\八岐大蛇\解锁阵容"
    soul_BQ_TCTZ = r"探索\御魂\八岐大蛇\退出挑战"
    soul_BQ_XZ = r"探索\御魂\八岐大蛇\选择八岐大蛇"
    soul_BQ_SDZR = r"探索\御魂\八岐大蛇\锁定阵容"
    soul_BQ_YS = r"探索\御魂\八岐大蛇\预设"
    soul_BQ_YSFZYH = r"探索\御魂\八岐大蛇\预设分组御魂"
    soul_BQ_YSZRCZ = r"探索\御魂\八岐大蛇\预设阵容出战"
    soul_BQ_YSZRXZ = r"探索\御魂\八岐大蛇\预设阵容协战"
    soul_BQ_YSZRBD = r"探索\御魂\八岐大蛇\预设阵容白蛋"
    soul_BQ_HELEVEN = r"探索\御魂\八岐大蛇\魂十一"
    soul_BQ_HONE = r"探索\御魂\八岐大蛇\魂一"
    soul_BQ_HTEN = r"探索\御魂\八岐大蛇\魂十"
    soul_BQ_ZDSL = r"探索\御魂\八岐大蛇\战斗胜利"
    soul_BQ_ZCTZ = r"探索\御魂\八岐大蛇\再次挑战"
    soul_BQ_YHTB = r"探索\御魂\御魂图标"
    soul_BQ_QD = r"探索\御魂\八岐大蛇\确定"


    user_SYTX = r"用户\首页头像"
    user_XZZH = r"用户\选择账号"

    demon_TY = r"町中\逢魔之时\庭院"
    demon_ZXJJ = r"町中\逢魔之时\左下集结"
    demon_ZCZJ = r"町中\逢魔之时\左侧战绩"
    demon_ZCJJ = r"町中\逢魔之时\左侧集结"
    demon_QD = r"町中\逢魔之时\确定"
    demon_ZDSL = r"町中\逢魔之时\战斗胜利"
    demon_ZDSB = r"町中\逢魔之时\战斗失败"
    demon_ZCTZ = r"町中\逢魔之时\再次挑战"
    demon_TCTZ = r"町中\逢魔之时\退出挑战"
    demon_JBFMZSRK = r"町中\逢魔之时\旧版逢魔之时入口"
    demon_XBFMZSRK = r"町中\逢魔之时\新版逢魔之时入口"
    demon_XSFM = r"町中\逢魔之时\现世逢魔"
    demon_HSDM = r"町中\逢魔之时\红色达摩"
    demon_HSDMYLQ = r"町中\逢魔之时\红色达摩已领取"
    demon_FMCSL = r"町中\逢魔之时\逢魔次数零"
    demon_FMLD = r"町中\逢魔之时\逢魔蓝点"
    demon_HDJL = r"町中\逢魔之时\获得奖励"
    demon_JJTZ = r"町中\逢魔之时\集结挑战"
    demon_YTYC = r"町中\逢魔之时\一天一次"
    demon_SL = r"町中\逢魔之时\首领"
    demon_SLJ = r"町中\逢魔之时\首领极"
    demon_YSJYXHDBSCH = r"町中\逢魔之时\右上角圆形红底白色叉号"
    demon_ZB = r"町中\逢魔之时\准备"
    demon_YJHD = r"町中\逢魔之时\印记获得"

    ghost_DJY = r"探索\地域鬼王\等级一"
    ghost_JH = r"探索\地域鬼王\减号"
    ghost_JRTZ = r"探索\地域鬼王\今日挑战"
    ghost_ZB = r"探索\地域鬼王\准备"
    ghost_DYGWTB = r"探索\地域鬼王\地域鬼王图标"
    ghost_TZ = r"探索\地域鬼王\挑战"
    ghost_SC = r"探索\地域鬼王\收藏"
    ghost_SCGW_NC = r"探索\地域鬼王\收藏鬼王\鸟巢"
    ghost_SCGW_SLSCJG = r"探索\地域鬼王\收藏鬼王\少林寺藏经阁"
    ghost_SCGW_DXS = r"探索\地域鬼王\收藏鬼王\丹霞山"
    ghost_W = r"探索\地域鬼王\无"
    ghost_PTBZ = r"探索\地域鬼王\普通标志"
    ghost_WXZ = r"探索\地域鬼王\未选择"
    ghost_JBZ = r"探索\地域鬼王\极标志"
    ghost_SX = r"探索\地域鬼王\筛选"
    ghost_SXGW = r"探索\地域鬼王\筛选鬼王"
    ghost_SXGW_NC = r"探索\地域鬼王\筛选鬼王\鸟巢"
    ghost_SXGW_SLSCJG = r"探索\地域鬼王\筛选鬼王\少林寺藏经阁"
    ghost_SXGW_DXS = r"探索\地域鬼王\筛选鬼王\丹霞山"
    ghost_SXGW_HHL = r"探索\地域鬼王\筛选鬼王\黄鹤楼"
    ghost_TCTZ = r"探索\结界突破\退出挑战"
    ghost_ZCTZ = r"探索\结界突破\再次挑战"
    ghost_ZDSB = r"探索\结界突破\战斗失败"
    ghost_ZDSL = r"探索\结界突破\战斗胜利"

    friends_YJSQ = r"好友\一键收取"
    friends_YJZF = r"好友\一键祝福"
    friends_XZYM = r"好友\协战已满"
    friends_YCXZ = r"好友\右侧协战"
    friends_YCTJ = r"好友\右侧添加"
    friends_YCHY = r"好友\右侧好友"
    friends_JW = r"好友\吉闻"
    friends_HYTB = r"好友\好友图标"
    friends_HYYM = r"好友\好友已满"
    friends_TJHY = r"好友\添加好友"
    friends_ZXHY = r"好友\左下好友"
    friends_HDJL = r"好友\获得奖励"
    friends_SQ = r"好友\申请"
    friends_ZFAN = r"好友\祝福按钮"
    friends_HYJBTS = r"好友\好友羁绊提升"


class Cvstrategy:
    # 图像文字识别类型
    sift = ["sift"]
    default = ["mstpl", "tpl", "sift", "brisk"]


if __name__ == '__main__':
    print(Onmyoji.user_SYTX)
